version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - locallibrary.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./locallibrary/database:/app/database
