version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: ["./entrypoint.sh"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./locallibrary/database:/app/database
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: {}
